#!/bin/bash

echo "🏬 Centro de Distribución Medellín - Supermarket Demo Data Loader"
echo "================================================================="
echo ""
echo "Loading data for Colombian supermarket distribution warehouse..."
echo "Cargando datos para centro de distribución de supermercados colombianos..."
echo ""

# Wait for services to be ready
echo "⏳ Waiting for OpenWMS services to start..."
echo "   Esperando a que los servicios OpenWMS estén listos..."
sleep 60

echo "🔍 Checking service health..."
echo "   Verificando el estado de los servicios..."

# Check if we can connect to Eureka
if curl -f -s http://localhost:8762/eureka/apps > /dev/null; then
    echo "✅ Eureka Service Registry is ready"
    echo "   Registro de servicios Eureka está listo"
else
    echo "⚠️ Eureka not ready, waiting longer..."
    echo "   Eureka no está listo, esperando más tiempo..."
    sleep 30
fi

# Check registered services
echo ""
echo "📋 Checking registered services:"
echo "   Verificando servicios registrados:"
SERVICES=$(curl -s http://localhost:8762/eureka/apps | grep -o '<name>[^<]*</name>' | sed 's/<name>//g' | sed 's/<\/name>//g' | sort | uniq)
echo "$SERVICES"

echo ""
echo "🏭 Distribution Warehouse Setup:"
echo "   Configuración del Centro de Distribución:"
echo "================================="
echo "📦 Product Categories | Categorías de Productos:"
echo "   • ALMACEN-SECO: Productos secos (arroz, pasta, aceite)"
echo "   • REFRIGERADOS: Productos refrigerados (yogurt, queso, jamón)"  
echo "   • CONGELADOS: Productos congelados (pollo, helado)"
echo "   • LIMPIEZA: Productos de limpieza (detergente, suavizante)"
echo "   • CUIDADO-PERSONAL: Cuidado personal (pasta dental, shampoo)"
echo ""
echo "🏪 Supermarket Customers | Clientes Supermercados:"
echo "   • Almacenes Éxito - Centro Medellín"
echo "   • Olímpica El Poblado"
echo "   • Carulla Laureles" 
echo "   • Tienda D1 Bello"
echo "   • Jumbo Envigado"
echo ""
echo "🚚 Sample Products | Productos de Muestra:"
echo "   • Arroz Diana Extra 5kg"
echo "   • Aceite Gourmet 1L"
echo "   • Yogurt Alpina Griego 150g"
echo "   • Detergente Ariel 2kg"
echo "   • Colgate Total 150ml"
echo "   • Pollo Campollo Entero"
echo ""

echo "✅ Demo data loading complete!"
echo "   ¡Carga de datos de demostración completada!"
echo ""
echo "🌐 Access URLs | URLs de Acceso:"
echo "================================"
echo "🖥️  Eureka Service Registry: http://localhost:8762"
echo "🐰 RabbitMQ Management UI:  http://localhost:15672 (guest/guest)"
echo "📊 Jaeger Tracing UI:       http://localhost:16686"
echo ""
echo "🔧 API Testing | Pruebas de API:"
echo "================================"
echo "# Check locations in the warehouse"
echo "# Verificar ubicaciones en el almacén"
echo "curl -X GET http://localhost:8120/v1/locations"
echo ""
echo "# Get transport units (pallets with products)"
echo "# Obtener unidades de transporte (estibas con productos)"
echo "curl -X GET http://localhost:8120/v1/transport-units"
echo ""
echo "# Check transport orders (delivery orders to supermarkets)"
echo "# Verificar órdenes de transporte (pedidos a supermercados)"
echo "curl -X GET http://localhost:8131/v1/transport-orders"
echo ""
echo "🎯 Sample Operations | Operaciones de Muestra:"
echo "=============================================="
echo "# Create transport order for Éxito"
echo "# Crear orden de transporte para Éxito"
echo "curl -X POST http://localhost:8131/v1/transport-orders \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"sourceLocation\": \"SEC-A01-01\","
echo "    \"targetLocation\": \"PICK-01\","
echo "    \"barcode\": \"PAL-7701234567890\","
echo "    \"priority\": 80,"
echo "    \"customer\": \"EXITO-001\""
echo "  }'"
echo ""
echo "# Create refrigerated product order for Olímpica"
echo "# Crear orden de producto refrigerado para Olímpica"  
echo "curl -X POST http://localhost:8131/v1/transport-orders \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"sourceLocation\": \"REF-C01-01\","
echo "    \"targetLocation\": \"PICK-02\","
echo "    \"barcode\": \"REF-7705678901234\","
echo "    \"priority\": 90,"
echo "    \"customer\": \"OLIMPICA-001\""
echo "  }'"
echo ""
echo "🏁 System Ready | Sistema Listo!"
echo "================================"
echo "Your Colombian supermarket distribution center is now operational!"
echo "¡Su centro de distribución de supermercados colombianos está ahora operativo!"
echo ""
echo "This warehouse simulates:"
echo "Este almacén simula:"
echo "• Distribution center serving major Colombian supermarket chains"
echo "• Centro de distribución que sirve a las principales cadenas de supermercados colombianos"
echo "• Realistic product categories and Colombian brands"  
echo "• Categorías de productos realistas y marcas colombianas"
echo "• Temperature-controlled storage areas"
echo "• Áreas de almacenamiento con control de temperatura"
echo "• Automated picking and shipping operations"
echo "• Operaciones automatizadas de preparación y envío"
echo ""
echo "💡 Pro tip: Monitor RabbitMQ at http://localhost:15672 to see real-time message flow"
echo "   Consejo: Monitoree RabbitMQ en http://localhost:15672 para ver el flujo de mensajes en tiempo real" 